services:
  backend:
    build: ./backend
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 5000:5000
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=exam

volumes:
  postgres_data:
